server:
    port: 8081
spring:
    profiles:
        active: local-product
        include: core

---
spring:
    graphql:
        graphiql:
            enabled: true
        schema:
            locations: classpath:graphql/**/
            file-extensions: .graphqls
    main:
        allow-bean-definition-overriding: true
    config:
        activate:
            on-profile: local-product
