version: "3"

services:
    database:
        container_name: postgresql
        image: postgres
        env_file:
            -   .env
        ports:
            -   "5432:5432"
        volumes:
            - ./data/postgres/:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    product-application:
        container_name: product_application
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            -   .env
        ports:
            -   "8090:8080"
        environment:
            SPRING_DATASOURCE_URL: ${DATABASE_URL}
            SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
            SPRING_DATASOURCE_PASSWORD": ${DATABASE_PASSWORD}
        command: bash -c "
            ls -al
            && ./gradlew :product-application:bootJar -Pprofile=local
            && java -jar -Dspring.profiles.active=local ./build/libs/product-application.jar
            "
        depends_on:
            -   database

