version: "3"

services:
    database:
        container_name: postgresql
        image: postgres
        env_file:
            -   .env
        ports:
            -   "5432:5432"
        volumes:
            - ./data/postgres/:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    product-application:
        container_name: product_application
        build:
            context: ./
            dockerfile: Dockerfile-product
        env_file:
            -   .env
        ports:
            - "8081:8081"
        environment:
            SPRING_DATASOURCE_URL: ${DATABASE_URL}
            SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
            SPRING_DATASOURCE_PASSWORD": ${DATABASE_PASSWORD}
        command: bash -c "
            java -jar -Dspring.profiles.active=local ./product-application/build/libs/product-application.jar
            "
        depends_on:
            -   database

    order-application:
        container_name: order_application
        build:
            context: ./
            dockerfile: Dockerfile-order
        env_file:
            - .env
        ports:
            - "8082:8082"
        environment:
            SPRING_DATASOURCE_URL: ${DATABASE_URL}
            SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
            SPRING_DATASOURCE_PASSWORD": ${DATABASE_PASSWORD}
        command: bash -c "
            java -jar -Dspring.profiles.active=local ./order-application/build/libs/order-application.jar
            "
        depends_on:
            - database

    payment-application:
        container_name: payment_application
        build:
            context: ./
            dockerfile: Dockerfile-payment
        env_file:
            - .env
        ports:
            - "8083:8083"
        environment:
            SPRING_DATASOURCE_URL: ${DATABASE_URL}
            SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
            SPRING_DATASOURCE_PASSWORD": ${DATABASE_PASSWORD}
        command: bash -c "
            java -jar -Dspring.profiles.active=local ./payment-application/build/libs/payment-application.jar
            "
        depends_on:
            - database

    shipping-application:
        container_name: shipping_application
        build:
            context: ./
            dockerfile: Dockerfile-shipping
        env_file:
            - .env
        ports:
            - "8084:8084"
        environment:
            SPRING_DATASOURCE_URL: ${DATABASE_URL}
            SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
            SPRING_DATASOURCE_PASSWORD": ${DATABASE_PASSWORD}
        command: bash -c "
            java -jar -Dspring.profiles.active=local ./shipping-application/build/libs/shipping-application.jar
            "
        depends_on:
            - database
