pay:
    kakao-pay:
        authentication:
            client-id: ${kakao-pay-client-id}
            client-secret: ${kakao-pay-client-secret}
            secret-key: ${kakao-pay-secret-key}
            secret-key-dev: ${kakao-pay-secret-key-dev}
        host:
            url: https://open-api.kakaopay.com
        endpoint:
            request-access-token: /oauth/token
    naver-pay:
        authentication:
            access-key: ''
            secret-key: ''
        host:
            url: ''
    toss-payments:
        authentication:
            access-key: ${toss-payments-client-key}
            secret-key: ${toss-payments-secret-key}
        host:
            url: https://api.tosspayments.com
        endpoint:
            approve: /v1/payments/confirm
    timeout:
        read-time: 30000
        connect-time: 30000
