pay:
    kakao-pay:
        authentication:
            access-key: ''
            secret-key: ''
        host:
            url: https://open-api.kakaopay.com
    naver-pay:
        authentication:
            access-key: ''
            secret-key: ''
        host:
            url: ''
    toss-payments:
        authentication:
            access-key: ${toss-payments-client-key}
            secret-key: ${toss-payments-secret-key}
        host:
            url: https://api.tosspayments.com
        endpoint:
            approve: /v1/payments/confirm
    timeout:
        read-time: 30000
        connect-time: 30000
