spring:
    mvc:
        servlet:
            load-on-startup: 1
    config:
        activate:
            on-profile: local-order
    batch:
        jdbc:
            initialize-schema: always
        job:
            enabled: false
    datasource:
        url: ${database-url}
        username: ${database-username}
        password: ${database-password}
        driver-class-name: org.postgresql.Driver
    kafka:
        consumer:
            bootstrap-servers: kafka-service:9092
            group-id: group-1
#            value-deserializer: org.springframework.kafka.support.serializer.ByteArrayDeserializer
#            properties:
#                spring:
#                    json:
#                        trusted:
#                            packages: '*'
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 1000
