name: Ktlint Continuous Integration

on:
    push:
        branches: [ develop, main ]
    pull_request:
        branches: [ develop, main ]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'

            - name: Run Lint
              run: |
                  ./gradlew clean ktlintCheck
